% function[] = Occupation_Number(iters,directory)

    cd 'D:\Lab\Salfi\KLVb_3D_Matlab\Results'
    directory = '20210204191832';
    iters=21;
    %load the results generated by the python code 
    fn = sprintf('%s/PythonResults/U_results.csv',directory);   
    load (fn);
    
    for d=1:iters
        fn = sprintf('%s/VE%d',directory,d);   
        load (fn,'E_sorted');
        mu_1(d)=mean([E_sorted(1) E_sorted(2)]);
    end
   
    E_0= zeros(iters,1);
    E_1= mu_1';
    E_2= 2*mu_1'+U_results*1000;

%     
%     occup_0= (E_1 > E_0) .* (E_2 > E_0);
%     occup_1= (E_2 > E_1) .* (E_0 > E_1);
%     occup_2= (E_1 > E_2) .* (E_0 > E_2);
%     
%     stem(1:iters, occup_0')
%     hold on
%     stem(1:iters, 2*occup_1')
%     stem(1:iters, 3*occup_2')
%     
%     xlim([0, iters+1])
%     ylim([0,2])
% % end
