% INPUTS: number of iterations, directory where results are located
% OUTPUTS: a plot allowing you to identify one-hole regime (not saved)
function[] = Occupation_Number(iters,directory,middle_values)

    cd 'D:\Lab\Salfi\KLVb_3D_Matlab\Results\Reduced_Gates'
    directory = '20210319005218';
    iters=34;
    %load the results generated by the python code 
    fn = sprintf('%s/PythonResults/U_results.csv',directory);   
    load (fn);
    
    for d=1:iters
        fn = sprintf('%s/VE%d',directory,d);   
        load (fn,'E_sorted');
        mu_1(d)=mean([E_sorted(1) E_sorted(2)]);
    end
   
    E_0= zeros(iters,1);
    E_1= mu_1';
    E_2= 2*mu_1'+U_results*1000;
    
    plot(middle_values, E_0)
    hold on
    grid on
    plot(middle_values, E_1)
    plot(middle_values, E_2)
    
end


